version: '3'

volumes:
  postgres_data:

services:
  db:
    container_name: sql-database
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
