version: '3'

services:
  db:
    container_name: sql-database
    image: postgres:13.0-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      # Скрипт для инициализации базы
      - ./db/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
